name: Publish Unity Package to GitHub Packages

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    if: >-
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Authenticate to GitHub Packages (npm registry)
      - name: Authenticate to GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      # Verify if the package.json version has changed
      - name: Check version change
        id: version_check
        run: |
          if git diff HEAD^ HEAD -- package.json | grep '"version"'; then
            echo "Version updated."
            echo "version_changed=true" >> $GITHUB_ENV
          else
            echo "No version change detected."
            echo "version_changed=false" >> $GITHUB_ENV
          fi
      # Stop the job if the version has not changed
      - name: Skip if no version change
        if: env.version_changed == 'false'
        run: |
          echo "Skipping publish because the version has not changed."
          exit 0

      # Verify Unity project structure
      - name: Verify Unity project structure
        run: |
          if [ ! -f "./package.json" ]; then
            echo "Error: package.json file is missing!" && exit 1
          fi

      # Build Unity Package (.tgz)
      - name: Build Unity Package (.tgz)
        run: |
          mkdir -p ./dist
          tar -czf ./dist/SakyoGameLib.tgz ./Runtime ./Editor ./package.json ./CHANGELOG.md ./README.md ./LICENSE.md

      # Verify .tgz package
      - name: Verify .tgz package
        run: |
          ls -lh ./dist/SakyoGameLib.tgz

      # Publish Unity Package to GitHub Packages with public access
      - name: Publish Unity Package to GitHub Packages
        run: |
          npm publish ./dist/SakyoGameLib.tgz
