name: Check if package.json or CHANGELOG.md are modified

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: |
          git fetch --prune --unshallow
          git fetch origin main
          git fetch origin ${{ github.head_ref }}

      - name: Get the list of modified files
        run: |
          # Fetch the list of files modified in the source branch (PR branch)
          CHANGES=$(git diff --name-only origin/main..origin/${{ github.head_ref }})
          echo "Modified files: $CHANGES"
          echo "CHANGES=$CHANGES" >> $GITHUB_ENV

      - name: Check if package.json and CHANGELOG.md are modified
        run: |
          # Check if both package.json and CHANGELOG.md are modified
          if [[ "$CHANGES" != *"package.json"* || "$CHANGES" != *"CHANGELOG.md"* ]]; then
            echo "Error: You must modify both package.json and CHANGELOG.md before making a pull request to the main branch."
            exit 1
          fi

      - name: Allow PR to continue
        run: echo "Required files (package.json and CHANGELOG.md) have been modified. PR can proceed."