name: Check if package.json or CHANGELOG.md are modified

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: |
          git fetch --prune --unshallow

      - name: Check if package.json and CHANGELOG.md is modified
        run: |
          # Compare the source branch with the main branch
          git fetch origin main  # S'assurer que la branche main est à jour
          CHANGES=$(git diff --name-only origin/main..${{ github.head_ref }})

          # Check if one of the specific files has been modified
          if [[ "$CHANGES" != *"package.json"* || "$CHANGES" != *"CHANGELOG.md"* ]]; then
            echo "Error: You must modify either package.json and CHANGELOG.md before making a pull request to the main branch."
            exit 1
          fi

      - name: Allow PR to continue
        run: echo "Required files (package.json and CHANGELOG.md) have been modified. PR can proceed."
